### ISSUE TITLE
Consider adding a License file

### ISSUE THREAD

**Issue by jwrubel** [monzo/progression-framework#18]
Hi! Thank you _so_ much for making this available! I notice you refer to the project as open source, so I'm wondering if you would be willing to add a license file to the repo based on the rights you are granting. Without one, it's technically considered "all rights reserved".

**Comment by lucasjohnston** [comment]
Hey @jwrubel 👋
Although open source, this project is under exclusive copyright of Monzo - hence there is no licence. I'd like to add a licence to this project, and it's on my to-do list to get this added. I'll use this issue in the PR when it is added so you're in the know 😄

**Comment by jwrubel** [comment]
Oh awesome! Adding a license won’t affect Monzo’s copyright, it just lets you specify how other people can use the work, if at all. https://choosealicense.com is pretty helpful if you’re trying to decide which license to use.

**Comment by lucasjohnston** [comment]
Done! Closing this issue :)
