### ISSUE TITLE
https://progression.monzo.com/ redirects to https://monzo.com/careers/

### ISSUE THREAD

**Issue by b099l3** [monzo/progression-framework#87]
Hi, just firstly wanted to say this is a great example of progression in our industry very clear and to the point. I am highly grateful for Monzo open-sourcing it.

I had shared it around my company as an example but it now seems to redirect to the careers site? Is this intended? I understand if there is a cost implication associated with hosting. Just wondered if there were plans to make it available or if we need to run it locally?

**Comment by aaa-paul** [comment]
Experiencing the same thing.

**Comment by b099l3** [comment]
From the Monzo web site going to "Transparency" then the "progression framework" seems to link to this URL https://eng-progression.monzo.com/ ... which also doesn't work. Possibly internal now?

**Comment by aaa-paul** [comment]
> From the Monzo web site going to "Transparency" then the "progression framework" seems to link to this URL https://eng-progression.monzo.com/ ... which also doesn't work. Possibly internal now?

@b099l3 , found a workaround that doesn't have the best experience but does provide all of the content: https://web.archive.org/web/20210128075956if_/https://progression.monzo.com/

**Comment by lucasjohnston** [comment]
Hey - just chanced upon this. The repo hasn't been updated much since I left Monzo, presuming the team's switched to using another system for progression internally :)
For reference it's still up on the Netlify subdomain here: https://monzo-progression.netlify.app

**Comment by aaa-paul** [comment]
> Hey - just chanced upon this. The repo hasn't been updated much since I left Monzo, presuming the team's switched to using another system for progression internally :)
> For reference it's still up on the Netlify subdomain here: https://monzo-progression.netlify.app
> 
> It's all under MIT - feel free to fork + host it yourself / adapt as desired, all the instructions are in the `README` and iirc most of the build/headers/other config is in `netlify.toml`

Thanks so much for the link!

**Comment by b099l3** [comment]
Yeah, thanks for the link! I'll close this

**Comment by b099l3** [comment]
This sheds some light on the changes to the progression framework at Monzo - https://monzo.com/blog/lessons-from-implementing-progression-frameworks-at-scale
